"""add bot_activity table

Revision ID: 4f4f87f96246
Revises: ad243352c772
Create Date: 2026-04-08 19:43:11.326023
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4f87f96246'
down_revision: Union[str, None] = 'ad243352c772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('market_id', sa.String(), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_time', 'bot_activity', ['timestamp'], unique=False)
    op.create_index('idx_activity_type', 'bot_activity', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_activity_type', table_name='bot_activity')
    op.drop_index('idx_activity_time', table_name='bot_activity')
    op.drop_table('bot_activity')
    # ### end Alembic commands ###
