"""initial schema

Revision ID: ad243352c772
Revises: 
Create Date: 2026-04-07 18:57:45.655217
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad243352c772'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit_breaker_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('starting_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('daily_pnl_pct', sa.Float(), nullable=False),
    sa.Column('is_tripped', sa.Boolean(), nullable=True),
    sa.Column('tripped_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('markets',
    sa.Column('condition_id', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('liquidity', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('neg_risk', sa.Boolean(), nullable=True),
    sa.Column('clob_token_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('outcome_prices', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('invested', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_bracket_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bracket', sa.String(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_pnl_win', sa.Float(), nullable=True),
    sa.Column('avg_pnl_loss', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bracket')
    )
    op.create_table('wallets',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('markets_traded', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_trade_size', sa.Float(), nullable=True),
    sa.Column('is_flagged_hashdive', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('ai_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.condition_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_cache_market', 'ai_cache', ['market_id', 'expires_at'], unique=False)
    op.create_table('market_volume_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('volume_1h', sa.Float(), nullable=True),
    sa.Column('volume_4h', sa.Float(), nullable=True),
    sa.Column('volume_24h', sa.Float(), nullable=True),
    sa.Column('trade_count_1h', sa.Integer(), nullable=True),
    sa.Column('avg_trade_size_1h', sa.Float(), nullable=True),
    sa.Column('price_change_1h', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.condition_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vol_snap_market_time', 'market_volume_snapshots', ['market_id', 'timestamp'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('trigger_wallets', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('trigger_trade_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('total_suspicious_volume', sa.Float(), nullable=True),
    sa.Column('market_price_at_detection', sa.Float(), nullable=True),
    sa.Column('time_to_resolution', sa.Interval(), nullable=True),
    sa.Column('web_context', sa.Text(), nullable=True),
    sa.Column('key_findings', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.condition_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('maker_address', sa.String(), nullable=True),
    sa.Column('taker_address', sa.String(), nullable=True),
    sa.Column('usd_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.condition_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trades_market_time', 'trades', ['market_id', 'timestamp'], unique=False)
    op.create_index('idx_trades_taker', 'trades', ['taker_address'], unique=False)
    op.create_index('idx_trades_timestamp', 'trades', ['timestamp'], unique=False)
    op.create_index('idx_trades_usd', 'trades', ['usd_value'], unique=False)
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('usd_invested', sa.Float(), nullable=False),
    sa.Column('usd_returned', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('score_at_entry', sa.Integer(), nullable=True),
    sa.Column('confidence_at_entry', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('highest_price_since_entry', sa.Float(), nullable=True),
    sa.Column('trailing_stop_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.condition_id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_trades')
    op.drop_index('idx_trades_usd', table_name='trades')
    op.drop_index('idx_trades_timestamp', table_name='trades')
    op.drop_index('idx_trades_taker', table_name='trades')
    op.drop_index('idx_trades_market_time', table_name='trades')
    op.drop_table('trades')
    op.drop_table('signals')
    op.drop_index('idx_vol_snap_market_time', table_name='market_volume_snapshots')
    op.drop_table('market_volume_snapshots')
    op.drop_index('idx_ai_cache_market', table_name='ai_cache')
    op.drop_table('ai_cache')
    op.drop_table('wallets')
    op.drop_table('score_bracket_stats')
    op.drop_table('portfolio')
    op.drop_table('markets')
    op.drop_table('circuit_breaker_state')
    # ### end Alembic commands ###
